class ResourceNotFoundException(ValueError):
    pass


class ResourceAlreadyExistsException(ValueError):
    pass
